apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-deployment
  namespace: default
  labels:
    app: portfolio-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-app
  template:
    metadata:
      labels:
        app: portfolio-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: portfolio-app
          image: europe-central2-docker.pkg.dev/portfolio-426015/portfolio/portfolio
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portfolio-app-config