services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: Dockerfile-prod
      args:
        - NUXT_APP_BASE_URL=${NUXT_APP_BASE_URL}
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/my-app
    ports:
      - 80:80
      - 443:443
